### ISSUE TITLE
Exception thrown while trying to toggle select widget mode

### ISSUE THREAD

**Issue by natintosh** [mateusfccp/prototype_constrained_box#3]
======== Exception caught by gesture ===============================================================
The following assertion was thrown while handling a gesture:
RenderBox was not laid out: RenderParagraph#ff814 NEEDS-LAYOUT NEEDS-PAINT
'package:flutter/src/rendering/box.dart':
Failed assertion: line 2165 pos 12: 'hasSize'

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

When the exception was thrown, this was the stack: 
#2      RenderBox.size (package:flutter/src/rendering/box.dart:2165:12)
#3      RenderBox.semanticBounds (package:flutter/src/rendering/box.dart:2317:44)
#4      _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:2805:32)
#5      _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:2800:11)
#6      _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:2800:11)
#7      _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:2800:11)
#8      _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:2800:11)
#9      _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:2800:11)
#10     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:2800:11)
#11     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:2800:11)
#12     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:2800:11)
#13     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:2800:11)
#14     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:2800:11)
#15     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:2800:11)
#16     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:2800:11)
#17     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:2800:11)
#18     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:2800:11)
#19     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:2800:11)
#20     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:2800:11)
#21     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:2800:11)
#22     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:2800:11)
#23     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:2800:11)
#24     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:2800:11)
#25     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:2800:11)
#26     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:2800:11)
#27     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:2800:11)
#28     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:2800:11)
#29     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:2800:11)
#30     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:2800:11)
#31     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:2800:11)
#32     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:2800:11)
#33     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:2800:11)
#34     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:2800:11)
#35     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:2800:11)
#36     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:2800:11)
#37     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:2800:11)
#38     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:2800:11)
#39     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:2800:11)
#40     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:2800:11)
#41     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:2800:11)
#42     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:2800:11)
#43     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:2800:11)
#44     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:2800:11)
#45     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:2800:11)
#46     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:2800:11)
#47     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:2800:11)
#48     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:2800:11)
#49     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:2800:11)
#50     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:2800:11)
#51     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:2800:11)
#52     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:2800:11)
#53     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:2800:11)
#54     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:2800:11)
#55     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:2800:11)
#56     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:2800:11)
#57     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:2800:11)
#58     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:2800:11)
#59     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:2800:11)
#60     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:2800:11)
#61     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:2800:11)
#62     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:2800:11)
#63     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:2800:11)
#64     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:2800:11)
#65     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:2800:11)
#66     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:2800:11)
#67     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:2800:11)
#68     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:2800:11)
#69     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:2800:11)
#70     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:2800:11)
#71     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:2800:11)
#72     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:2800:11)
#73     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:2800:11)
#74     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:2800:11)
#75     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:2800:11)
#76     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:2800:11)
#77     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:2800:11)
#78     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:2800:11)
#79     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:2800:11)
#80     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:2800:11)
#81     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:2800:11)
#82     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:2800:11)
#83     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:2800:11)
#84     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:2800:11)
#85     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:2800:11)
#86     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:2800:11)
#87     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:2800:11)
#88     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:2800:11)
#89     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:2800:11)
#90     _WidgetInspectorState.hitTest (package:flutter/src/widgets/widget_inspector.dart:2832:5)
#91     _WidgetInspectorState._inspectAt (package:flutter/src/widgets/widget_inspector.dart:2853:41)
#92     _WidgetInspectorState._handlePanUpdate (package:flutter/src/widgets/widget_inspector.dart:2865:5)
#93     DragGestureRecognizer._checkUpdate.<anonymous closure> (package:flutter/src/gestures/monodrag.dart:806:55)
#94     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:344:24)
#95     DragGestureRecognizer._checkUpdate (package:flutter/src/gestures/monodrag.dart:806:7)
#96     DragGestureRecognizer.handleEvent (package:flutter/src/gestures/monodrag.dart:652:11)
#97     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:98:12)
#98     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:143:9)
#99     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:633:13)
#100    PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:141:18)
#101    PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:127:7)
#102    GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:495:19)
#103    GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:475:22)
#104    RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:425:11)
#105    GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:420:7)
#106    GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:383:5)
#107    GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:330:7)
#108    GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:299:9)
#109    _invoke1 (dart:ui/hooks.dart:328:13)
#110    PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:442:7)
#111    _dispatchPointerDataPacket (dart:ui/hooks.dart:262:31)
(elided 2 frames from class _AssertionError)
Handler: "onUpdate"
Recognizer: PanGestureRecognizer#30e96
  debugOwner: GestureDetector
  start behavior: start

**Comment by mateusfccp** [comment]
Hello, @natintosh.

Thank you for the report.

Could you please provide a minimum reproducible example, so I can investigate further?

**Comment by natintosh** [comment]
Steps to recreate:

* Create a Widget that uses PrototypeConstrainedBox and Run
* Enable Flutter Inspector and Toggle Select Widget Mode
* Try selecting that Widget

```dart

@override
  Widget buildContent(BuildContext context) {
    return Row(
      crossAxisAlignment: CrossAxisAlignment.center,
      children: [
        ConstrainedBox(
          constraints: BoxConstraints.tight(
            Size.square(48),
          ),
          child: DecoratedBox(
            decoration: BoxDecoration(
              borderRadius: BorderRadius.circular(64),
              color: Colors.grey,
            ),
            child: LayoutBuilder(builder: imageBuilder),
          ),
        ),
        SizeBox(width: 16),
        Expanded(
          child: Padding(
            padding: EdgeInsets.symmetric(
              vertical: 12,
            ),
            child: PrototypeConstrainedBox.tightFor(
              height: true,
              prototype: const HeaderDescription(
                header: '1',
                description: '1\n2',
              ),
              child: HeaderDescription(
                header: header,
                description: description,
              ),
            ),
          ),
        ),
      ],
    );
  }


class HeaderDescription extends StatelessWidget {
  const HeaderDescription({
    super.key,
    this.header,
    this.headerStyle,
    this.description,
    this.descriptionStyle,
    this.action,
  });

  final String? header;
  final String? description;

  @override
  Widget build(BuildContext context) {
    return Column(
      mainAxisAlignment: MainAxisAlignment.center,
      crossAxisAlignment:  CrossAxisAlignment.start,
      children: [
        if ((header ?? '').isNotEmpty)
          Text(
            header ?? '',
            maxLines: 1,
          ),
        if ((header ?? '').isNotEmpty && (description ?? '').isNotEmpty)
          12
        if ((description ?? '').isNotEmpty)
          Text(
            description ?? '',
            maxLines: 2,
          ),
      ],
    );
  }
}
```

**Comment by mateusfccp** [comment]
I can reproduce the issue without problems in the `example` app.

**Comment by mateusfccp** [comment]
@natintosh Can you test against `master`? It should be fixed in the latest commit.

**Comment by natintosh** [comment]
The issue has been fixed thanks

**Comment by mateusfccp** [comment]
I'm releasing version `2.0.3` with the fix. It should take 10 minutes most.
